language: ruby
rvm:
- 2.7.3
before_install:
- gem install bundler:2.2.25
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: QuUcS08HyNhsX3SkvQLh3DBtFxEzNJK8idrmDyz9gO+BRhD321jzLiU81BMnUM4LDDlckdvBM5yEyPrgl1DPS3vg3ZjLmidWzYX7HYJ/N2KWWitXUy6fcAqqngYubJnwg44lMxyUQgmgC23Ag1eqL+AS51rAKrt+pA6SMMAGv4fwHDD+S8plhvOZno0MEPI0Ppkwq43C7THan4wknYEnsFTtptBB8dn+KAkVSO30OG5m0VenlZVazFmIK+LoEPRCBqtoPncpBdevy6DXAOQrV7m2C8QH/3TG6BG9PKpPnhZke71veWyX9K/rs6dtV1zjrKXbnlcLYmNv+p9KkJlhCtxEtfIRusK339zYwPh8ymkdssj2b9KjI6w85vT5UQ4rbiukipuG51wl68vtb9MhXAVb1mcxWVkFCoXb3HH0/u15Po57FNe6o5frxFDqyYFhZivrQJEMThe/KfQQSUw02W2Nhr21EB+/p7mb1P24OBsJ+l5E+Jx0w5/AYkwI0rp3snH+tb9dI4A/apLBvGoyhPfMhm3j9bhczQDjWULe/KmYQ8BbtmHZySbHlfn+QptQQWzYSQmiEth4klToBLUT8qaeOyBzbW96tQjrzhY+jQAFljqShf1ZKGFOXkgwDWKgC/v/rLF907ognRuQXFYSvnRYviNH+NQhUgyIbuofprc=
