version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: deploy
          command: bundle exec rake site:deploy
workflows:
  build-and-test:
    jobs:
      - deploy
