version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8a:f8:fd:01:f9:65:96:8f:f5:20:be:b6:55:e0:7b:9f"
      - checkout
      - ruby/install-deps
      - run:
          name: deploy
          command: bundle exec rake site:deploy
workflows:
  build-and-test:
    jobs:
      - deploy
